apiVersion: v1
kind: Service
metadata:
  name: web-api-service
  namespace: production # Production için 'production' yap
spec:
  type: ClusterIP
  ports:
    - port: 8000        # Ingress'in hedeflediği servis portu
      targetPort: 8000  # Web container'ının dinlediği port
      name: http
  selector:
    app: web