apiVersion: v1  
kind: Po
metadata:
  name : firstpod
  labels:
    app: front-end
  
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80