apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup-cronjob
  namespace: production
  labels:
    app.kubernetes.io/name: db-backup
    tier: database
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
            app.kubernetes.io/name: db-backup
            tier: database
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            tier: database
          tolerations:
            - key: "workload"
              operator: "Equal"
              value: "database"
              effect: "NoSchedule"
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: db-backup-pvc
          containers:
            - name: postgres-backup
              image: docker.io/library/postgres:16-alpine
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                  BACKUP_FILE="/backups/backup_customer_orders_${TIMESTAMP}.sql.gz"
                  
                  echo ">>> [BACKUP START] OCI Block Volume uzerine yedekleme baslatildi: $(date)"
                  
                  # Kalici diske .sql.gz dump simulasyonu
                  echo "-- OCI Block Volume Backup: customer_orders $(date) --" | gzip > "${BACKUP_FILE}"
                  
                  echo ">>> [SAVED] Dosya kalici diske yazildi:"
                  ls -lh /backups/
                  
                  echo ">>> [SUCCESS] Islem tamamlandi."
                  exit 0
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi