apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true      # Git'ten silinen kaynaklari kumedeki siler
      selfHeal: true   # Terminalden yapilan degisiklikleri aninda Git'teki haline dondurur
    syncOptions:
      - CreateNamespace=true
