# ==============================================================================
# Stable & Canary Services + Base Rollout (v1 - Blue)
# ==============================================================================

apiVersion: v1
kind: Service
metadata:
  name: payment-service-stable
  namespace: production
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-canary
  namespace: production
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: payment-service
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: payment-service
  namespace: production
  labels:
    app: payment-service
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: payment-service
  strategy:
    canary:
      canaryService: payment-service-canary
      stableService: payment-service-stable
      trafficRouting: {} # Service seviyesinde agirliklandirma simulasyonu
      steps:
        - setWeight: 25
        - pause: { duration: 1m }
        - setWeight: 50
        - pause: { duration: 2m }
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      nodeSelector:
        tier: web
      containers:
        - name: payment-api
          image: docker.io/argoproj/rollouts-demo:blue
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: COLOR
              value: "blue"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
